import Head from "next/head";
import { Suspense } from "react";
import { Canvas, useLoader } from "@react-three/fiber";
import { Environment, OrbitControls } from "@react-three/drei";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import Xbot from "@/components/Xbot";

const ModelHouse = () => {
  const gltf = useLoader(GLTFLoader, "/models/city.glb");

  return (
    <>
      <primitive object={gltf.scene} scale={0.1} />
    </>
  );
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>CB - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="globe">
        <Canvas
          className="bg-blue-500"
          shadows
          dpr={[1, 2]}
          camera={{ position: [1.8, 0.7, 3.5], fov: 50 }}
        >
          <ambientLight intensity={5} />
          <spotLight
            intensity={30}
            angle={20}
            penumbra={1}
            position={[30, 15, 10]}
            castShadow
          />
          <Suspense fallback={null}>
            <ModelHouse />
            <Environment preset="city" />
          </Suspense>
          <OrbitControls
            minDistance={1} // set the minimum distance to 2 units
            maxDistance={5} // set the maximum distance to 5 units
            maxPolarAngle={Math.PI / 2 - 0.05} // set the minimum angle to 45 degrees
            minPolarAngle={Math.PI / 4 }
            enablePan={false}
            // enableDamping={true}
          />
        </Canvas>
      </div>
    </div>
  );
}
